spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 10GB

  storage:
    default-path: D:\\StorageService
